name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 0 * * 1' # This runs the workflow every Monday at midnight UTC
    workflow_dispatch:  # This allows you to manually trigger the workflow via GitHub UI
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                feed_list: "https://medium.com/feed/@praneet9"
